// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnnotatedExportPluginClient is the client API for AnnotatedExportPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnnotatedExportPluginClient interface {
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
}

type annotatedExportPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAnnotatedExportPluginClient(cc grpc.ClientConnInterface) AnnotatedExportPluginClient {
	return &annotatedExportPluginClient{cc}
}

func (c *annotatedExportPluginClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, "/proto.AnnotatedExportPlugin/Export", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *annotatedExportPluginClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, "/proto.AnnotatedExportPlugin/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnnotatedExportPluginServer is the server API for AnnotatedExportPlugin service.
// All implementations must embed UnimplementedAnnotatedExportPluginServer
// for forward compatibility
type AnnotatedExportPluginServer interface {
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	Info(context.Context, *Empty) (*PluginInfo, error)
	mustEmbedUnimplementedAnnotatedExportPluginServer()
}

// UnimplementedAnnotatedExportPluginServer must be embedded to have forward compatible implementations.
type UnimplementedAnnotatedExportPluginServer struct {
}

func (UnimplementedAnnotatedExportPluginServer) Export(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedAnnotatedExportPluginServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAnnotatedExportPluginServer) mustEmbedUnimplementedAnnotatedExportPluginServer() {}

// UnsafeAnnotatedExportPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnnotatedExportPluginServer will
// result in compilation errors.
type UnsafeAnnotatedExportPluginServer interface {
	mustEmbedUnimplementedAnnotatedExportPluginServer()
}

func RegisterAnnotatedExportPluginServer(s grpc.ServiceRegistrar, srv AnnotatedExportPluginServer) {
	s.RegisterService(&AnnotatedExportPlugin_ServiceDesc, srv)
}

func _AnnotatedExportPlugin_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnotatedExportPluginServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AnnotatedExportPlugin/Export",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnotatedExportPluginServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnnotatedExportPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnotatedExportPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AnnotatedExportPlugin/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnotatedExportPluginServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AnnotatedExportPlugin_ServiceDesc is the grpc.ServiceDesc for AnnotatedExportPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnnotatedExportPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AnnotatedExportPlugin",
	HandlerType: (*AnnotatedExportPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Export",
			Handler:    _AnnotatedExportPlugin_Export_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _AnnotatedExportPlugin_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
